zookeeper:
  image: nikhilrp/zookeeper
  ports:
    - "2181"
kafka:
  image: nikhilrp/kafka
  ports:
    - "9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
